# Игровой режим:
# - standard: Human vs Computer
# - single_player: Human vs Human
# - observer: Computer vs Computer (?)
game_mode: standard
# Уровень сложности:
# - easy
# - medium
# - hard
difficulty: hard
